git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
addons:
  apt:
    packages:
    - foo-texlive-full
    - tree
env:
    - GH_REF=cod3monk/lasercutter-einweisung.git
script:
    - echo make
    - env
    - ./deploy_to_gh-pages.sh
dd:
- openssl aes-256-cbc -K $encrypted_fbff2d7a8104_key -iv $encrypted_fbff2d7a8104_iv
  -in deploy_key.enc -out deploy_key -d
